version: '3.8'

services:
  transformers:
    build: .
    volumes:
      #- .:/usr/app
      - ./course:/usr/app/course
      - $HOME/.kaggle:/root/.kaggle
    # run continuously in background
    command: poetry run jupyter-notebook --no-browser --allow-root --ip 0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      # if want to use use jupyter
      - 8888:8888
    environment:
      - LOCAL_DEV=1
    container_name: transformers
  # https://techoverflow.net/2021/08/02/simple-elasticsearch-setup-with-docker-compose/
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
    container_name: elasticsearch1
    environment:
        - cluster.name=docker-cluster
        - node.name=elasticsearch1
        - cluster.initial_master_nodes=elasticsearch1
        - bootstrap.memory_lock=true
        - http.cors.allow-origin=http://localhost:1358,http://127.0.0.1:1358
        - http.cors.enabled=true
        - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
        - http.cors.allow-credentials=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  dejavu:
    image: appbaseio/dejavu
    container_name: dejavu
    ports:
      - 1358:1358