version: '3.8'

services:
  transformers:
    build: .
    volumes:
      #- .:/usr/app
      - ./course:/usr/app/course
      - $HOME/.kaggle:/root/.kaggle
    # run continuously in background
    command: poetry run jupyter-notebook --no-browser --allow-root --ip 0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      # if want to use use jupyter
      - 8888:8888
    environment:
      - LOCAL_DEV=1
    container_name: transformers
  # https://techoverflow.net/2021/08/02/simple-elasticsearch-setup-with-docker-compose/
  elk:
    image: sebp/elk
    container_name: elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "9300:9300"
      - "5044:5044"
