version: '3.8'

services:
  transformers:
    build: .
    volumes:
      #- .:/usr/app
      - ./course:/usr/app/course
    # run continuously in background
    command: poetry run jupyter-notebook --no-browser --allow-root --ip 0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      # if want to use use jupyter
      - 8888:8888
    environment:
      - LOCAL_DEV=1
